version: '3.7'

services:
  django_app:
    build: .
    env_file:
      - .env
    volumes:
      - static_vol:/app/static
      - media_vol:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
 

  nginx:
    build: ./nginx
    volumes:
      - static_vol:/app/static
      - media_vol:/app/media
    ports:
      -  "80:80"
    depends_on:
      - django_app

volumes:
  postgres_data:
  static_vol:
  media_vol:




